# Generated by Django 3.0.7 on 2020-07-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishmarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
