# Generated by Django 3.0.7 on 2020-07-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishmarket', '0002_auto_20200701_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
