# Generated by Django 3.0.7 on 2020-07-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishmarket', '0003_game_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='Unnamed Game', max_length=32),
        ),
    ]
