databases:
  - name: meenkari
    plan: free
    databaseName: meenkari
    user: meenkari

services:
  - type: web
    name: meenkari
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "daphne meenkari.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meenkari
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4