# Generated by Django 4.2.3 on 2023-07-06 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(blank=True, max_length=127)),
                ('lobby_id', models.CharField(blank=True, max_length=127)),
                ('game_name', models.CharField(default='Unnamed Game', max_length=32)),
                ('game_privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('game_status', models.CharField(choices=[('empty', 'Empty'), ('united', 'United'), ('started', 'Started'), ('over', 'Over'), ('stopped', 'Stopped')], default='empty', max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('lastmodify_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('p1_hand', models.TextField(blank=True)),
                ('p2_hand', models.TextField(blank=True)),
                ('p3_hand', models.TextField(blank=True)),
                ('p4_hand', models.TextField(blank=True)),
                ('p5_hand', models.TextField(blank=True)),
                ('p6_hand', models.TextField(blank=True)),
                ('team_1_status', models.CharField(blank=True, max_length=40)),
                ('team_2_status', models.CharField(blank=True, max_length=40)),
                ('p0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p0', to=settings.AUTH_USER_MODEL)),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2', to=settings.AUTH_USER_MODEL)),
                ('p3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p3', to=settings.AUTH_USER_MODEL)),
                ('p4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p4', to=settings.AUTH_USER_MODEL)),
                ('p5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p5', to=settings.AUTH_USER_MODEL)),
                ('p6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p6', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby', to='meenkari.game')),
                ('players', models.ManyToManyField(blank=True, related_name='lobby_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
