# Generated by Django 3.0.8 on 2020-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meenkari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_privacy',
            field=models.CharField(choices=[('Public', 'public'), ('Private', 'private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='unite_id',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('Empty', 'empty'), ('United', 'united'), ('Started', 'started'), ('Over', 'over'), ('Stopped', 'stopped')], default='open', max_length=10),
        ),
    ]
