# Generated by Django 3.0.8 on 2020-07-12 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meenkari', '0002_auto_20200711_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_11_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_12_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_13_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_21_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_22_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_23_image',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('Empty', 'empty'), ('United', 'united'), ('Started', 'started'), ('Over', 'over'), ('Stopped', 'stopped')], default='empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
