# Generated by Django 3.0.8 on 2020-07-12 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meenkari', '0005_auto_20200712_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitequeue',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='unite_queue_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
