# Generated by Django 3.0.8 on 2020-07-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meenkari', '0006_auto_20200712_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_11',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_11_hand',
            new_name='p1_hand',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_12',
            new_name='p2',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_12_hand',
            new_name='p2_hand',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_13',
            new_name='p3',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_13_hand',
            new_name='p3_hand',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_21',
            new_name='p4',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_21_hand',
            new_name='p4_hand',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_22',
            new_name='p5',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_22_hand',
            new_name='p5_hand',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_23',
            new_name='p6',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_23_hand',
            new_name='p6_hand',
        ),
    ]
