# Generated by Django 3.0.8 on 2020-07-31 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meenkari', '0008_auto_20200718_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='unite_id',
            new_name='lobby_id',
        ),
        migrations.DeleteModel(
            name='UniteQueue',
        ),
        migrations.AddField(
            model_name='lobby',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby', to='meenkari.Game'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='lobby_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
